# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1488205714);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1488205834);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1488808056);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1488205594);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1488808176);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1488205954);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 40);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1488807945878");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1488809851878");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1488807946774");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1488811546774");
user_pref("browser.search.countryCode", "PL");
user_pref("browser.search.region", "PL");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20161214045259");
user_pref("browser.startup.homepage_override.buildID", "20161214045259");
user_pref("browser.startup.homepage_override.mstone", "50.1.0");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 2);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20170306);
user_pref("datareporting.sessions.current.activeTicks", 2);
user_pref("datareporting.sessions.current.firstPaint", 1732);
user_pref("datareporting.sessions.current.main", 20);
user_pref("datareporting.sessions.current.sessionRestored", 1663);
user_pref("datareporting.sessions.current.startTime", "1488808586648");
user_pref("datareporting.sessions.current.totalTime", 11);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1488205230144,\"a\":105,\"t\":4009,\"c\":true,\"m\":723,\"fp\":6679,\"sr\":6175}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1488807933161,\"a\":57,\"t\":315,\"c\":true,\"m\":662,\"fp\":6957,\"sr\":6758}");
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("e10s.rollout.cohort", "test");
user_pref("e10s.rollout.cohortSample", "0.675011");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"firefox@getpocket.com\":{\"version\":\"1.0.5\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"e10srollout@mozilla.org\":{\"version\":\"1.5\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"aushelper@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/aushelper@mozilla.org.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":true},\"langpack-pl@firefox.mozilla.org\":{\"version\":\"50.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-pl@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10s.rollout.blocklist", "{dc572301-7619-498c-a57d-39143191b318}");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "50allmpc");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:50.1.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1488205715);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160826.01");
user_pref("extensions.lastAppVersion", "50.1.0");
user_pref("extensions.lastPlatformVersion", "50.1.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.5\",\"st\":1481692523000},\"webcompat@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1481692523000},\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.5\",\"st\":1481692523000},\"aushelper@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/aushelper@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1481692523000}},\"app-global\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"51.0.1\",\"st\":1485486806000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"51.0.1\",\"st\":1485486806000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"50.1.0\",\"st\":1481692523000},\"langpack-pl@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-pl@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"50.0.2\",\"st\":1480613446000}}}");
user_pref("idle.lastDailyNotification", 1488808649);
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1488205297);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20161214045259");
user_pref("media.gmp-manager.lastCheck", 1488808000);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1488206381);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("services.blocklist.addons.checked", 1487902967);
user_pref("services.blocklist.clock_skew_seconds", 302866);
user_pref("services.blocklist.last_etag", "\"1487895540022\"");
user_pref("services.blocklist.last_update_seconds", 1487902967);
user_pref("services.blocklist.onecrl.checked", 1487902967);
user_pref("services.blocklist.plugins.checked", 1487902967);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1488206380);
user_pref("toolkit.startup.last_success", 1488808586);
user_pref("toolkit.telemetry.cachedClientID", "59bc6840-fabd-45db-b2a6-c2a9908b0304");
user_pref("toolkit.telemetry.previousBuildID", "20161214045259");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
